version: "3.9"

services:
  p5-sketch:
    container_name: p5-sketch
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ..:/usr/src/app
      # - ../_docker/node_modules:/usr/src/node_modules
    # command: npm start
    command: npm start
    # command: npx http-server /app -p 8080
    # stdin_open: true
    # tty: true
